const ComponentTypes = Object.freeze({
    CAPTURE: 'CAPTURE',
    DISPENSER: 'DISPENSER',
    FEEDER: 'FEEDER',
    DATAINPUT: 'DATA_INPUT',
    DATAOUTPUT: 'DATA_OUTPUT',
    USERINPUT: 'USER_INPUT',
    USEROUTPUT: 'USER_OUTPUT',
    MEDIAINPUT: 'MEDIA_INPUT',
    MEDIAOUTPUT: 'MEDIA_OUTPUT',
    STORAGE: 'STORAGE',
    DISPLAY: 'DISPLAY',
    NETWORK: 'NETWORK',
    BAGGAGESCALE: 'BAGGAGE_SCALE',
    INSERTIONBELT: 'INSERTION_BELT',
    VERIFICATIONBELT: 'VERIFICATION_BELT',
    PARKINGBELT: 'PARKING_BELT',
    ANNOUNCEMENT: 'ANNOUNCEMENT',
    APPLICATION: 'APPLICATION'
});

export { ComponentTypes };