const DataStatus = Object.freeze({
    OK: 'DS_OK',
    CORRUPTED: 'DS_CORRUPTED',
    INCOMPLETE: 'DS_INCOMPLETE',
    ZEROLENGTH: 'DS_ZEROLENGTH',
    DOCUMENTAUTHENTICATIONFAILED: 'DS_DOCUMENT_AUTHENTICATION_FAILED',
    INVALID: 'DS_INVALID',
    MISMATCH: 'DS_MISMATCH'
});

export { DataStatus };