const DeviceTypes = Object.freeze({
    NONAPPLICABLEDEVICETYPE: 'NON_APPLICABLE_DEVICE_TYPE',
    PRINT: 'PRINT',
    READ: 'READ',
    MOTORIZED: 'MOTORIZED',
    DIP: 'DIP',
    SWIPE: 'SWIPE',
    CONTACTLESS: 'CONTACTLESS',
    HANDHELD: 'HANDHELD',
    INSERT: 'INSERT',
    DISPENSE: 'DISPENSE',
    CAPTURE: 'CAPTURE',
    CONVEYOR: 'CONVEYOR',
    SCALE: 'SCALE',
    CAMERA: 'CAMERA',
    FLATBED: 'FLATBED',
    CHIPANDPIN: 'CHIP_AND_PIN',
    EXTERNAL: 'EXTERNAL',
    BIOMETRICS: 'BIOMETRICS',
    ASSISTIVE: 'ASSISTIVE',
    ILLUMINATION: 'ILLUMINATION',
    DISPLAY: 'DISPLAY'
});

export { DeviceTypes };