const MediaTypes = Object.freeze({
    CARD: 'CARD',
    MAGCARD: 'MAGCARD',
    CHIP: 'CHIP',
    BARCODE: 'BARCODE',
    TICKET: 'TICKET',
    RECEIPT: 'RECEIPT',
    BOARDINGPASS: 'BOARDINGPASS',
    BAGGAGETAG: 'BAGGAGETAG',
    HEAVYTAG: 'HEAVYTAG',
    RFIDBAGGAGETAG: 'RFID_BAGGAGETAG',
    BAGGAGE: 'BAGGAGE',
    PASSPORT: 'PASSPORT',
    IDCARD: 'IDCARD',
    VISA: 'VISA',
    DRIVERLICENSE: 'DRIVERLICENSE',
    RFID: 'RFID',
    NFC: 'NFC',
    OCR: 'OCR',
    IMAGE: 'IMAGE',
    PRINTED: 'PRINTED',
    AUDIO: 'AUDIO',
    VISUAL: 'VISUAL',
    TOUCH: 'TOUCH',
    DATASTRUCTURE: 'DATASTRUCTURE'
});

export { MediaTypes };