const NavigationTypes = Object.freeze({
    NONAPPLICABLENAVIGATIONTYPE: 'NON_APPLICABLE_NAVIGATION_TYPE',
    NAVPAD5KEY: 'NAVPAD_5_KEY',
    NAVPAD8KEY: 'NAVPAD_8_KEY',
    AUDIONAV6KEY: 'AUDIONAV_6_KEY',
    AUDIONAV6KEYBAR: 'AUDIONAV_6_KEY_BAR'
});

export { NavigationTypes };